/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2014-01-07 08:13:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import lodlinker.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	String output = request.getParameter("output");
	String service = request.getParameter("service");
	String query = request.getParameter("query");

	String server = "./LLservlet.jsp";
	if (query != null || service != null) {
		if (!"HTML".equals(output) && output != null) {
			//String query = request.getParameter("query");
			System.out.println(output);

      out.write('\n');
      if (true) {
        _jspx_page_context.forward("./LLservlet.jsp" + (("./LLservlet.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("query", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(query), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("output", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(output), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("service", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(service), request.getCharacterEncoding()));
        return;
      }
      out.write('\n');

		}
	} else {
		if (!"HTML".equals(output) && output != null) {
			String key = request.getParameter("keyword");
			String uri = request.getParameter("uri");
			String lod = request.getParameter("lod");
			String limit = request.getParameter("limit");
			String offset = request.getParameter("offset");

			if (key != null) {
				String sparql = "select distinct ?uri ?label ?LOD ?LOD_label ?type where{{?uri lodcu:describedIn ?LOD FILTER regex(STR(?uri),\""
						+ key + "\",\"i\").}union{";
				sparql += "?uri rdfs:label ?l FILTER regex(?l,\"" + key
						+ "\",\"i\").} ?uri lodcu:describedIn ?LOD.";
				sparql += "?LOD rdfs:label ?LOD_label;";
				sparql += "a ?type.OPTIONAL{?uri rdfs:label ?label}}";

				if (limit != null) {
					sparql += "limit " + limit;
				}
				if (offset != null) {
					sparql += " offset " + offset;
				}

      out.write('\n');
      if (true) {
        _jspx_page_context.forward("./LLservlet.jsp" + (("./LLservlet.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("query", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(sparql), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("output", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(output), request.getCharacterEncoding()));
        return;
      }
      out.write('\n');

			} else if (uri != null) {
				String sparql = "select distinct ?uri ?label ?LOD ?LOD_label ?type where{<"
						+ uri + "> lodcu:describedIn ?LOD.";
				sparql += "?LOD rdfs:label ?LOD_label;";
				sparql += "a ?type.";
				sparql += "?uri lodcu:describedIn ?LOD FILTER (?uri = <"
						+ uri + ">).";
				sparql += "OPTIONAL {?uri rdfs:label ?label}}";

				if (limit != null && !"".equals(limit)) {
					sparql += "limit " + limit;
				}
				if (offset != null && !"".equals(offset)) {
					sparql += " offset " + offset;
				}

      out.write('\n');
      if (true) {
        _jspx_page_context.forward("./LLservlet.jsp" + (("./LLservlet.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("query", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(sparql), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("output", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(output), request.getCharacterEncoding()));
        return;
      }
      out.write('\n');

			} else if (lod != null) {
				String sparql = "select distinct ?uri ?label ?LOD ?LOD_label ?type where{?uri lodcu:describedIn <"+ lod +">.";
				sparql += "?uri lodcu:describedIn ?LOD. FILTER (?LOD=<"+ lod +">)";
				sparql += "?LOD rdfs:label ?LOD_label;";
				sparql += "a ?type.OPTIONAL{?uri rdfs:label ?label}}";

				if (limit != null && !"".equals(limit)) {
					sparql += "limit " + limit;
				}
				if (offset != null && !"".equals(offset)) {
					sparql += " offset " + offset;
				}

      out.write('\n');
      if (true) {
        _jspx_page_context.forward("./LLservlet.jsp" + (("./LLservlet.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("query", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(sparql), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("output", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(output), request.getCharacterEncoding()));
        return;
      }
      out.write('\n');

			}
		}
	}

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\"> <![endif]-->\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\"> <![endif]-->\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\"> <![endif]-->\n");
      out.write("<!--[if gt IE 8]><!-->\n");
      out.write("<html class=\"no-js\">\n");
      out.write("<!--<![endif]-->\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<title>LODlinker</title>\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/normalize.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"content/font/elusive-icons/css/elusive-webfont.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\">\n");
      out.write("\n");
      out.write("<script src=\"js/vendor/modernizr-2.6.2.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("\twindow.jQuery\n");
      out.write("\t\t\t|| document.write(\n");
      out.write("\t\t\t\t\t'<script src=\"js/vendor/jquery-1.10.2.min.js\"><\\/script>')\n");
      out.write("</script>\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\n");
      out.write("<script src=\"js/plugins.js\"></script>\n");
      out.write("<script src=\"js/connector.js\"></script>\n");
      out.write("<script src=\"js/main.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!--[if lt IE 7]>\n");
      out.write("            <p class=\"browsehappy\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\n");
      out.write("        <![endif]-->\n");
      out.write("\n");
      out.write("\t<!-- Add your site or application content here -->\n");
      out.write("\t<div class=\"main container text-center\">\n");
      out.write("\t\t<div class=\"title row\">\n");
      out.write("\t\t\t<div class=\"span12\">\n");
      out.write("\t\t\t\t<a href=\"/\"><img src=\"./img/title.png\" width=\"250\" class=\"img\"></a><br>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<p>URIやキーワードを入力し、それが記述されているLODを検索するためのサイトです。</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"search_result row\">\n");
      out.write("\t\t\t<div class=\"span10 offset1\">\n");
      out.write("\t\t\t\t<div id=\"table\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"row search_form\">\n");
      out.write("\t\t\t<div class=\"span12\">\n");
      out.write("\t\t\t\t<p>URI検索</p>\n");
      out.write("\t\t\t\t<form class=\"form-inline\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"例:http://dbpedia.org/ontology/Book\"\n");
      out.write("\t\t\t\t\t\tclass=\"input-xxlarge\"\n");
      out.write("\t\t\t\t\t\tonKeyPress=\"return goSubmit_uri(event, $(this));\"> <input\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"LOD検索\" class=\"btn-small btn-info\"\n");
      out.write("\t\t\t\t\t\tonclick=\"goResult_uri($(this))\"\">\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\n");
      out.write("\t\t\t\t<p>キーワード検索</p>\n");
      out.write("\t\t\t\t<form class=\"form-inline\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"例:Book\"\n");
      out.write("\t\t\t\t\t\tonKeyPress=\"return goSubmit_key(event, $(this));\"> <input\n");
      out.write("\t\t\t\t\t\ttype=\"button\" value=\"LOD検索\" class=\"btn-small btn-info\"\n");
      out.write("\t\t\t\t\t\tonclick=\"goResult_key($(this))\">\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"foot row\">\n");
      out.write("\t\t\t<div class=\"span12\">\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t<a href=\"about.html\">about(使い方)</a> | <a href='#addModal'\n");
      out.write("\t\t\t\t\t\tdata-toggle='modal'>LODを登録</a> | <a href='viewLOD.jsp'>LOD一覧</a> |\n");
      out.write("\t\t\t\t\t<a href='contact.html'>contact</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"modal hide fade\" id=\"myModal\">\n");
      out.write("\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">SPARQL検索</h4>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body span12\" id=\"mbody\">\n");
      out.write("\t\t\t\t\t<div id=\"mess1\"></div>\n");
      out.write("\t\t\t\t\t<br> クエリ入力\n");
      out.write("\t\t\t\t\t<form id=\"form1\">\n");
      out.write("\t\t\t\t\t\t<textarea class=\"span4\" id=\"query_sparql\" rows=6></textarea>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t<input type=\"button\" class=\"btn btn-primary\" value=\"クエリ送信\"\n");
      out.write("\t\t\t\t\t\tonclick=\"querySend()\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"modal hide fade\" id=\"myModal_ins\">\n");
      out.write("\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">URI詳細情報</h4>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body\" id=\"mbody_ins\">\n");
      out.write("\t\t\t\t\t<div id=\"modal_ins_table\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"modal hide fade\" id=\"addModal\">\n");
      out.write("\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">LODを登録</h4>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body span12\" id=\"mbody2\">\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\tタイプ <select selected=\"selected\" id=\"modal_select\"\n");
      out.write("\t\t\t\t\t\t\tonchange=\"changeSelect()\"><option value=\"SPARQLEndPoint\">SPARQLエンドポイント</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"rdfFILE\">RDFファイル</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<hr width=\"450\">\n");
      out.write("\t\t\t\t\t<div id=\"modal_main\">\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"inputURL\">URL</label>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputURL\" placeholder=\"LODのURL\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"inputTitle\">タイトル</label>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputTitle\" placeholder=\"タイトル(ラベル)\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"control-group hide\" id=\"ftype_s\">\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\" for=\"inputFtype\">ファイル形式</label>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inputFtype\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"RDF/XML or TTL or N-TRIPLE or N3\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn-primary\" onclick=\"addLOD()\">登録</button>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->\n");
      out.write("\t<script>\n");
      out.write("\t\t(function(b, o, i, l, e, r) {\n");
      out.write("\t\t\tb.GoogleAnalyticsObject = l;\n");
      out.write("\t\t\tb[l] || (b[l] = function() {\n");
      out.write("\t\t\t\t(b[l].q = b[l].q || []).push(arguments)\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\tb[l].l = +new Date;\n");
      out.write("\t\t\te = o.createElement(i);\n");
      out.write("\t\t\tr = o.getElementsByTagName(i)[0];\n");
      out.write("\t\t\te.src = '//www.google-analytics.com/analytics.js';\n");
      out.write("\t\t\tr.parentNode.insertBefore(e, r)\n");
      out.write("\t\t}(window, document, 'script', 'ga'));\n");
      out.write("\t\tga('create', 'UA-XXXXX-X');\n");
      out.write("\t\tga('send', 'pageview');\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\t<textarea id=\"shadowTextarea\" style=\"display: none\">\n");
      out.write("\n");
      out.write("</textarea>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
